### ISSUE TITLE
_DABOM_prep.Rmd re-build error

### ISSUE THREAD

**Issue by mackerman44** [KevinSee/PITcleanr#26]
Attempted to install `PITcleanr` using `remotes::install_github()` and `build_vignettes = T`, but there appears to be an error building the "_DABOM_prep.Rmd" doc, resulting in a failure to install PITcleanr. Error pasted below. It appears to be associated with not being able to find the "_compress-data.Rmd" which has maybe been renamed to "compress_data.Rmd"? It seems all other vignettes are re-building just fine.

   --- re-building '_DABOM_prep.Rmd' using rmarkdown
   Warning in file(con, "r") :
     cannot open file './child_docs/_compress-data.Rmd': No such file or directory
   
   Quitting from lines 73-73 [unnamed-chunk-4] (./child_docs/_compress-data.Rmd)
   Error: processing vignette '_DABOM_prep.Rmd' failed with diagnostics:
   cannot open the connection
   --- failed re-building '_DABOM_prep.Rmd'

**Comment by mackerman44** [comment]
verified that `remotes::install_github("mackerman44/PITcleanr@main", build_vignettes = F, force = T)` works just fine when not building vignettes.

**Comment by KevinSee** [comment]
Completed a temporary fix by adding `_DABOM_prep.Rmd` to the `.Rbuildignore` file. Now `PITcleanr` will install while we continue to revised `_DABOM_prep.Rmd`.

**Comment by KevinSee** [comment]
`_DABOM_prep.Rmd` has been replaced by `quick_prep.Rmd` in the vignettes. Before deleting `_DABOM_prep`, I'd like to double-check it's no longer needed, or that any information in it is explained in other vignettes like `quick_prep`.

**Comment by KevinSee** [comment]
I went through `_DABOM_prep`, and determined that all the information contained there is in another vignette. Either the `quick_prep` vignette, or more details in the `Prep_PIT_data` vignette.

Based on that, I deleted the `_DABOM_prep` vignette, and dropped it from the `.Rbuildignore` file.
