### ISSUE TITLE
Nez Perce need these functions?

### ISSUE THREAD

**Issue by KevinSee** [KevinSee/PITcleanr#33]
These functions are not used by Kevin See when running PITcleanr, but before deleting I wanted to check if Nez Perce researchers still used them.

- `obsNetwork`: I think this has been superseded by `buildNodeGraph` and `plotNodes`
- `defineRepGrps`: this is very specific to Lower Granite version of DABOM, and has a lot hard-coded into it. Might consider making part of the Nez Perce workflow, moving it out of `PITcleanr`
- `filterLGRtrapDB`: if still needed, consider making part of the Nez Perce workflow, moving it out of `PITcleanr`
- `summariseValidTagsLGR`: if still needed, consider making part of the Nez Perce workflow, moving it out of `PITcleanr`

**Comment by mackerman44** [comment]
I think you can go ahead and remove each of these functions from PITcleanr.
* In skimming through my workflow thus far, I don't use `obsNetwork()`
* I don't see a use for `defineRepGrps()`. Reporting groups change, and if needed, I can create my own function for the Snake River basin
* I'm not sure I'll even use it, but I've copy pasted `filterLGRtrapDB()` into my SRB_OncorPopStatus repo.
* Same goes for `summariseValidTagsLGR()`. I've copy/pasted over, no need to keep in PITcleanr.

**Comment by KevinSee** [comment]
All functions have been removed.
