### ISSUE TITLE
`compressDART()` doesn't re-assign to nodes

### ISSUE THREAD

**Issue by mackerman44** [KevinSee/PITcleanr#43]
I'd need to dig into this a tad more, but adding an Issue as a reminder.

When using `compressDART()` recently, observations were not re-assigned to nodes provided in `configuration` when the `node` differed from the `site_code`. For example, after using `buildConfig(node_assign = "array", array_suffix = "UD")` each of my two-pass array sites were split into downstream "_D" and upstream "_U" nodes and that `configuration` was provided to `compressDART()`; however, my results assigned observations only to `site_code`, not `node`. 

In looking at `compressDART()`, which uses `queryObsDART()`, observations are downloaded from "http://www.cbr.washington.edu/dart/cs/data/nezperce/. In looking at one of the downloads
[(nptspawn_GRA_2019_1.csv)](https://github.com/KevinSee/PITcleanr/files/13029874/nptspawn_GRA_2019_1.csv), 
it appears that the information is there to assign observations to nodes (config and antennagroupname columns).

Is it worth modifying `compress()` or compressDART()` so that it can re-assign detections to nodes when desired? I need to dig into the order-of-operations and functions more, not certain how big of a lift this might be.

**Comment by KevinSee** [comment]
@mackerman44 , check out the develop branch of PITcleanr. I just updated the `compressDART` function: turns out it wasn't making use of the configuration file at all. I think that's fixed the issue, but want to get your confirmation before I close this.

**Comment by mackerman44** [comment]
Looks like whatever you did worked! Thanks @KevinSee , I'll close this issue now.
