### ISSUE TITLE
queryTestTag - fails because it needs a tag code

### ISSUE THREAD

**Issue by ryankinzer** [KevinSee/PITcleanr#47]
The function includes a `stopifnot()` for a tag code which should be excluded.

**Comment by KevinSee** [comment]
Not sure what this issue is referring to now. I did recently rename `queryTestTagSite` to `queryTimerTagSite` to better reflect what is going on, but it never asks for a tag code. Can you provide more information @ryankinzer ?

**Comment by ryankinzer** [comment]
I don't think this applies anymore.  I found the function on the PITcleanr website before the workshop but it's no longer there. I think you fixed it in your sleep.
